name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies & Build
        run: |
          npm ci
          npx prisma generate
          npm run build

      - name: Zip Build Assets
        run: zip -r build.zip .next public package.json package-lock.json next.config.ts prisma scripts

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build.zip"
          target: "/home/ubuntu/manifestia-"

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/manifestia-
            # Unzip overrides existing files
            unzip -o build.zip
            # Install only production dependencies
            npm install --production
            # Regen prisma client
            npx prisma generate
            # Restart App
            pm2 restart manifestia
            # Cleanup
            rm build.zip
